Foreground yes
LogTime yes
LogClean no
LogSyslog no
LogFile /dev/stdout
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
StreamMaxLength 2048M
MaxScanSize 4095M
MaxFileSize 2048M
MaxRecursion 24
MaxFiles 10000
AlertExceedsMax yes
AlertEncrypted yes
AlertEncryptedArchive yes
AlertOLE2Macros yes
ReadTimeout 300
CommandReadTimeout 30
MaxThreads 2
SelfCheck 600
