import Link from 'next/link';import {notFound} from 'next/navigation';import {accountApi} from '@createcanyon/web/server';import {PageHeading,EmptyState,DataTable,Badge,money} from '@createcanyon/web/components';import {Operation} from '../../components/actions';
const collections:Record<string,{title:string;columns:string[]}>={moderation:{title:'Content moderation',columns:['item_title','seller_name','version_label','status','opened_at']},sellers:{title:'Seller restrictions',columns:['display_name','country_code','status','payouts_enabled','payout_hold_until']},copyright:{title:'Copyright claims',columns:['title','claimant_name','claimant_email','status','created_at']},payments:{title:'Payments & refund controls',columns:['order_number','status','total_minor','currency','refunded_minor']},refunds:{title:'Refund requests',columns:['id','order_line_id','amount_minor','currency','status','reason']},disputes:{title:'Payment disputes',columns:['provider_dispute_id','status','amount_minor','currency','created_at']},support:{title:'Support operations',columns:['subject','status','created_at']},reviews:{title:'Review moderation',columns:['item_title','rating','title','body','status']},ledger:{title:'Double-entry ledger',columns:['code','type','currency','debit_minor','credit_minor']},jobs:{title:'Background job health',columns:['event_type','attempts','max_attempts','processed_at','failed_at','last_error']},audit:{title:'Tamper-evident audit trail',columns:['sequence','actor_type','action','resource_type','resource_id','record_hash','created_at']}};
const reason={name:'reason',label:'Reason (retained in the audit trail)',kind:'textarea' as const};
function value(row:any,key:string){const v=row[key];if(v===null||v===undefined)return '—';if(key.endsWith('_at')||key==='payout_hold_until')return new Date(v).toLocaleString('en-AU');if(typeof v==='boolean')return v?'Yes':'No';if(typeof v==='object')return JSON.stringify(v);return String(v);}
export default async function Page({params}:{params:Promise<{section:string}>}){const {section}=await params;const config=collections[section];if(!config)notFound();const rows=await accountApi<any[]>('admin','admin/'+section);let integrity:any=null;if(section==='audit')integrity=await accountApi('admin','admin/audit/integrity');return <><PageHeading eyebrow="RESTRICTED OPERATIONS" title={config.title}>Server-side role checks apply to every read and action. Latest 200 records are shown.</PageHeading>{integrity&&<section className="panel"><h2>Audit-chain verification</h2><pre className="legal-text">{JSON.stringify(integrity,null,2)}</pre></section>}{rows.length?<DataTable headings={[...config.columns.map(c=>c.replaceAll('_',' ')),'Details / action']}>{rows.map((row:any,index:number)=><tr key={row.id??row.sequence??index}>{config.columns.map(c=><td className="audit-value" key={c}>{c==='status'?<Badge>{value(row,c)}</Badge>:value(row,c)}</td>)}<td>
 {section==='moderation'&&<Link className="button secondary small" href={'/moderation/'+row.id}>Review files & decide</Link>}
 {section==='support'&&<Link className="button secondary small" href={'/support/'+row.id}>Open conversation</Link>}
 {section==='sellers'&&<details><summary>Change restrictions</summary><Operation path={`admin/sellers/${row.id}/restrictions`} fields={[{name:'status',label:'Seller status',options:['PENDING_VERIFICATION','ACTIVE','RESTRICTED','SUSPENDED','CLOSED'],defaultValue:row.status},{name:'payoutHoldUntil',label:'Hold payouts until (blank clears hold)',kind:'datetime-local'},reason]}/></details>}
 {section==='copyright'&&<details><summary>Review claim</summary><p className="preserve-lines">{row.allegation}</p><pre className="legal-text">{JSON.stringify(row.evidence,null,2)}</pre><Operation path={`admin/copyright/${row.id}/status`} fields={[{name:'status',label:'Claim status',options:['OPEN','VALIDATING','CONTENT_DISABLED','SELLER_RESPONSE','COUNTER_NOTICE','RESTORED','UPHELD','CLOSED'],defaultValue:row.status},reason]}/></details>}
 {section==='payments'&&<details><summary>Order lines / refund</summary>{(row.lines??[]).map((line:any)=><section key={line.id}><h3>{line.title}</h3><p>{money(line.totalMinor,row.currency)} · {line.id}</p><Operation path="admin/refunds" label="Request line refund" initial={{orderLineId:line.id}} fields={[{name:'amountMinor',label:'Refund amount in minor units',kind:'number',defaultValue:line.totalMinor},reason]}/></section>)}</details>}
 {section==='reviews'&&<details><summary>Change visibility</summary><Operation path={`admin/reviews/${row.id}/status`} fields={[{name:'status',label:'Visibility',options:['PUBLISHED','HIDDEN','REMOVED'],defaultValue:row.status},reason]}/></details>}
 {section==='jobs'&&row.failed_at&&<details><summary>Requeue failed job</summary><p>Inspect and reconcile external provider effects before retrying financial jobs. This does not reset provider-attempt timestamps.</p><Operation path={`admin/jobs/${row.id}/requeue`} label="Requeue job" fields={[reason]}/></details>}
 {['refunds','disputes','ledger','audit'].includes(section)&&<details><summary>Recorded data</summary><pre className="legal-text">{JSON.stringify(row,null,2)}</pre></details>}
 </td></tr>)}</DataTable>:<EmptyState title="No records to show"/>}</>;}
