import Link from 'next/link';
import {notFound} from 'next/navigation';
import {headers} from 'next/headers';
import {ApiError,publicApi,storefrontContext,appUrl} from '@createcanyon/web/server';
import {Badge,money} from '@createcanyon/web/components';
import {AddToCart,ActionButton} from '@createcanyon/web/client';
async function item(slug:string){const c=await storefrontContext();try{return await publicApi('/v1/catalog/'+c.key+'/'+encodeURIComponent(slug));}catch(e){if(e instanceof ApiError&&e.status===404)notFound();throw e;}}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const data=await item((await params).slug);return {title:data.title,description:data.description.slice(0,155),alternates:{canonical:data.canonicalUrl},openGraph:{title:data.title,description:data.description.slice(0,200),...(data.previews?.[0]?.mimeType?.startsWith('image/')?{images:[data.previews[0].url]}:{})}};}
export default async function ItemPage({params}:{params:Promise<{slug:string}>}){
 const data=await item((await params).slug);const nonce=(await headers()).get('x-nonce')??undefined;
 const structured={'@context':'https://schema.org','@type':'Product',name:data.title,description:data.description,sku:data.itemId,brand:{'@type':'Brand',name:data.sellerDisplayName},offers:{'@type':'Offer',url:data.canonicalUrl,priceCurrency:data.currency,price:(data.amountMinor/100).toFixed(2),availability:'https://schema.org/InStock'},...(data.reviewCount?{aggregateRating:{'@type':'AggregateRating',ratingValue:data.rating,reviewCount:data.reviewCount}}:{})};
 return <div className="shell page"><script nonce={nonce} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\u003c')}}/><nav className="breadcrumbs"><Link href="/catalog">Explore assets</Link> / {data.categoryName??data.assetType.replaceAll('_',' ')} / {data.title}</nav><div className="item-layout"><div>
  <header className="item-header"><p className="eyebrow">{data.assetType.replaceAll('_',' ')}</p><h1>{data.title}</h1><p className="creator">by <Link href={'/sellers/'+encodeURIComponent(data.sellerSlug)}>{data.sellerDisplayName}</Link> · Version {data.versionLabel} · {data.rating>0?`★ ${Number(data.rating).toFixed(1)} (${data.reviewCount} reviews)`:'No reviews yet'}</p></header>
  {data.previews?.length?data.previews.map((p:any)=><div key={p.id} className="item-preview">{p.mimeType.startsWith('image/')?<img src={p.url} alt={`Preview of ${data.title}`}/>:p.mimeType.startsWith('audio/')?<audio controls preload="metadata" src={p.url} aria-label={`Audio preview of ${data.title}`}/>:<p>Preview format is not supported by this browser.</p>}</div>):<div className="item-preview"><div style={{textAlign:'center'}}><span className="item-placeholder" aria-hidden="true">◇</span><p className="muted">A public preview is not available for this release.</p></div></div>}
  <section className="panel"><h2>About this asset</h2><div className="prose">{data.description}</div><dl className="details-grid"><dt>Asset type</dt><dd>{data.assetType.replaceAll('_',' ')}</dd><dt>Release</dt><dd>{data.versionLabel}</dd><dt>AI involvement</dt><dd>{data.aiDisclosure}</dd><dt>Seller</dt><dd>{data.sellerDisplayName}</dd>{Object.entries(data.itemMetadata??{}).slice(0,20).map(([k,v])=><div key={k} style={{display:'contents'}}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl></section>
  {data.changelog&&<section className="panel"><h2>Release notes</h2><div className="prose">{data.changelog}</div></section>}
  <section className="panel"><h2>License options</h2>{data.licenses.map((l:any)=><details key={l.licenseVariantId}><summary>{l.name} · {money(l.amountMinor,l.currency)}</summary><p>{l.summary}</p><pre className="license-text">{l.bodyMarkdown}</pre><small>Template version {l.version}. The exact purchased terms are preserved with your order.</small></details>)}</section>
  <section className="panel"><h2>Reviews from buyers</h2>{data.reviews?.length?data.reviews.map((r:any)=><article key={r.id} className="review"><div className="review-meta"><span>{'★'.repeat(r.rating)}</span><Badge tone="positive">Verified purchase</Badge><span>{r.displayName??'Buyer'}</span></div><h3>{r.title}</h3><p>{r.body}</p>{r.sellerResponse&&<blockquote>Seller response: {r.sellerResponse}</blockquote>}</article>):<p className="muted">Buyers with an active purchase can leave a review from their library.</p>}</section>
 </div><aside className="stack"><AddToCart listingId={data.listingId} licenses={data.licenses} dashboardUrl={appUrl('dashboard')}/><div className="panel"><h3>A connected purchase</h3><p className="muted">Your order is held by the CreateCanyon Network and may include products from multiple independent sellers.</p><ActionButton path={'wishlist/'+data.itemId}>Save to wishlist</ActionButton></div><div className="panel"><h3>Need help with rights?</h3><p className="muted">Report suspected copyright infringement for review by the network’s trust team.</p><Link className="button text" href={'/report/'+data.itemId}>Report this item →</Link></div></aside></div></div>;
}
