import Link from 'next/link';
import {publicApi,storefrontContext,appUrl} from '@createcanyon/web/server';
import {EmptyState,ProductCard,type Listing} from '@createcanyon/web/components';
const channelCopy:Record<string,{title:string;accent:string;description:string}>={
 createcanyon:{title:'Big ideas start with',accent:'the right assets.',description:'Discover design, audio, documents and code from independent creators. Five specialist worlds. One connected marketplace.'},
 graphicgrounds:{title:'Give your next idea',accent:'a visual advantage.',description:'Explore photos, graphics, vectors and design templates made for your next creative project.'},
 melodymerchant:{title:'Find the sound',accent:'your story needs.',description:'Discover music, sound effects and audio loops from independent musicians and sound designers.'},
 filefoyer:{title:'From a blank page',accent:'to a brilliant start.',description:'Build with business documents, presentations and spreadsheets made to move your work forward.'},
 programplaza:{title:'Less starting over.',accent:'More building.',description:'Discover code, plugins and developer tools, with versioned releases and clear license records.'}
};
export default async function Home({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const query=await searchParams,channel=await storefrontContext(),copy=channelCopy[channel.key]!;
 const single=(key:string)=>typeof query[key]==='string'?query[key] as string:undefined;
 const q=single('q')??'',category=single('category')??'',sort=single('sort')??'newest',page=Math.max(1,Number(single('page')??1)||1);
 const params=new URLSearchParams({channel:channel.key,q,sort,page:String(page),pageSize:'12'});if(category)params.set('category',category);if(single('assetType'))params.set('assetType',single('assetType')!);
 let catalog:{items:Listing[];total:number;page:number;pageSize:number}|null=null;let categories:{slug:string;name:string}[]=[];let unavailable=false;
 try{[catalog,categories]=await Promise.all([publicApi('/v1/catalog?'+params),publicApi('/v1/storefronts/'+channel.key).then(r=>r.categories??[])]);}catch{unavailable=true;}
 const filtered=!!q||!!category;const link=(values:Record<string,string>)=>{const next=new URLSearchParams();if(q)next.set('q',q);if(category)next.set('category',category);if(sort!=='newest')next.set('sort',sort);for(const[k,v]of Object.entries(values)){if(v)next.set(k,v);else next.delete(k);}return '/catalog?'+next.toString()+'#catalog';};
 return <div className="shell">
  {!filtered&&page===1&&<><section className="hero" aria-labelledby="hero-title"><div><p className="eyebrow"><span className="dot"/>CREATED FOR WHAT COMES NEXT</p><h1 id="hero-title">{copy.title}<br/><em>{copy.accent}</em></h1><p className="lede">{copy.description}</p><form className="search-bar" action="/catalog" role="search"><label className="sr-only" htmlFor="hero-search">Search marketplace assets</label><span className="search-icon" aria-hidden="true">⌕</span><input id="hero-search" name="q" placeholder="What are you creating today?" maxLength={200}/><button className="button primary" type="submit">Find assets ↗</button></form><div className="popular"><span>Explore:</span>{(categories.length?categories.slice(0,3):[{slug:'',name:'All assets'}]).map(c=><Link key={c.name} href={link({category:c.slug})}>{c.name}</Link>)}</div></div>
   <div className="hero-composition" aria-hidden="true"><div className="composition-grid"/><div className="composition-disk"/><div className="sample-sheet"><span>CREATIVITY, IN GOOD COMPANY</span><strong>Your next<br/>great<br/>thing.</strong><small>FIND YOUR STARTING POINT ↗</small></div><div className="sample-sun"/><div className="sample-tile"><span>✳</span></div><span className="composition-caption">Made for the way you create.</span></div></section>
   <div className="trust-row"><div><span className="trust-icon">◇</span><span><strong>Independent creators</strong><small>One connected network</small></span></div><div><span className="trust-icon">▤</span><span><strong>Versioned licenses</strong><small>Your purchase, preserved</small></span></div><div><span className="trust-icon">↙</span><span><strong>A shared library</strong><small>All your purchases together</small></span></div><div><span className="trust-icon">◎</span><span><strong>Private originals</strong><small>Purchase-controlled downloads</small></span></div></div></>}
  <section id="catalog" className={filtered?'page':''} aria-labelledby="catalog-heading"><div className="section-heading"><div><h2 id="catalog-heading">{q?`Results for “${q}”`:category?categories.find(c=>c.slug===category)?.name??'Explore this category':'Fresh finds for your next project'}</h2><p>{catalog?`${catalog.total} available ${catalog.total===1?'asset':'assets'} on ${channel.name}`:'Browse this channel’s published collection.'}</p></div><a className="button text" href={appUrl('dashboard')+'/wishlist'}>Your wishlist ↗</a></div>
   <form className="filters" action="/catalog"><Link className={'filter-pill'+(!category?' selected':'')} href={link({category:'',page:''})}>All assets</Link>{categories.slice(0,7).map(c=><Link key={c.slug} className={'filter-pill'+(category===c.slug?' selected':'')} href={link({category:c.slug,page:''})}>{c.name}</Link>)}
    <input type="hidden" name="q" value={q}/><input type="hidden" name="category" value={category}/><div className="sort-control"><label htmlFor="sort">Sort</label><select id="sort" name="sort" defaultValue={sort}><option value="newest">Newest</option><option value="relevance">Relevance</option><option value="rating">Highest rated</option><option value="sales">Best selling</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select><button className="button secondary small">Apply</button></div></form>
   {filtered&&<form className="search-bar" action="/catalog" role="search" style={{marginBottom:28}}><label className="sr-only" htmlFor="results-search">Search assets</label><input id="results-search" name="q" defaultValue={q} maxLength={200}/><button className="button primary">Search</button></form>}
   {unavailable?<EmptyState title="The storefront is ready. The catalog is not connected yet.">The marketplace API is unavailable. Configure API_BASE_URL, start the API, apply the database migrations and seed development content. No demonstration products are being presented as live inventory.</EmptyState>:catalog?.items.length?<div className="product-grid">{catalog.items.map(item=><ProductCard key={item.listingId} item={item}/>)}</div>:<EmptyState title={filtered?'No matching assets yet.':'A new collection starts here.'}>{filtered?'Try a different search or category.':'Published, reviewed items will appear here when they are available.'}</EmptyState>}
   {catalog&&catalog.total>catalog.pageSize&&<nav className="pagination" aria-label="Catalog pages">{page>1&&<Link className="button secondary" href={link({page:String(page-1)})}>← Previous</Link>}<span>Page {page} of {Math.ceil(catalog.total/catalog.pageSize)}</span>{page*catalog.pageSize<catalog.total&&<Link className="button secondary" href={link({page:String(page+1)})}>Next →</Link>}</nav>}
  </section>
  <section className="seller-banner"><div><p className="eyebrow">BUILT BY CREATORS. FOR CREATORS.</p><h2>Your work deserves the right audience.</h2><p>Upload once. Choose your eligible channels. Manage everything from one seller account.</p></div><a className="button dark" href={appUrl('dashboard')+'/sell'}>Become a creator ↗</a></section>
 </div>;
}
