'use client';
import Script from 'next/script';import {useEffect,useRef,useState,type FormEvent} from 'react';import {api} from '@createcanyon/web/client';
type StripeClient={elements:(options:unknown)=>{create:(type:string)=>{mount:(element:HTMLElement)=>void;destroy:()=>void};submit:()=>Promise<{error?:{message?:string}}>};confirmPayment:(options:unknown)=>Promise<{error?:{message?:string}}>};
declare global{interface Window{Stripe?:(key:string)=>StripeClient;}}
export function Checkout({cartId,publishableKey,taxRequired,orderId}:{cartId:string;publishableKey:string;taxRequired:boolean;orderId?:string}){
 const [key]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[payment,setPayment]=useState<any>(null),[stripeReady,setStripeReady]=useState(false);
 const target=useRef<HTMLDivElement>(null),stripe=useRef<StripeClient|null>(null),elements=useRef<ReturnType<StripeClient['elements']>|null>(null);
 useEffect(()=>{if(!payment?.clientSecret||!stripeReady||!target.current||!publishableKey||!window.Stripe)return;stripe.current=window.Stripe(publishableKey);const e=stripe.current.elements({clientSecret:payment.clientSecret});elements.current=e;const paymentElement=e.create('payment');paymentElement.mount(target.current);return()=>paymentElement.destroy();},[payment,stripeReady,publishableKey]);
 async function prepare(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const d=new FormData(event.currentTarget);try{const result=await api(orderId?`orders/${orderId}/payment`:'checkout',{method:'POST',idempotencyKey:key,body:{cartId,successUrl:window.location.origin+'/orders',cancelUrl:window.location.origin+'/cart',...(taxRequired?{billingAddress:{line1:d.get('line1'),line2:d.get('line2')||undefined,city:d.get('city'),state:d.get('state')||undefined,postal_code:d.get('postal_code'),country:String(d.get('country')).toUpperCase()}}:{})}});if(result.mode==='stub'||result.mode==='free'||!result.clientSecret){window.location.assign('/orders/'+result.orderId);return;}setPayment(result);}catch(e){setError(e instanceof Error?e.message:'Checkout failed');}finally{setBusy(false);}}
 async function pay(){if(!elements.current||!stripe.current)return;setBusy(true);setError('');try{const submission=await elements.current.submit();if(submission.error)throw new Error(submission.error.message??'Check your payment details');const result=await stripe.current.confirmPayment({elements:elements.current,confirmParams:{return_url:window.location.origin+'/orders/'+payment.orderId}});if(result.error)throw new Error(result.error.message??'Payment could not be confirmed');}catch(e){setError(e instanceof Error?e.message:'Payment failed');}finally{setBusy(false);}}
 return <section className="panel"><h2>Network checkout</h2><p>Your order may contain products from several independent creators. Prices and availability are checked again before payment.</p>{publishableKey&&<Script src="https://js.stripe.com/v3/" onReady={()=>setStripeReady(true)} onError={()=>setError('The secure payment form could not load. No payment has been submitted.')}/>}{!payment?<form className="form-stack" onSubmit={prepare}>{taxRequired&&!orderId&&<><h3>Billing address</h3><label>Address line 1<input name="line1" autoComplete="billing address-line1" required maxLength={200}/></label><label>Address line 2<input name="line2" autoComplete="billing address-line2" maxLength={200}/></label><div className="form-grid"><label>City<input name="city" required autoComplete="billing address-level2" maxLength={100}/></label><label>State / region<input name="state" autoComplete="billing address-level1" maxLength={100}/></label><label>Postal code<input name="postal_code" required autoComplete="billing postal-code" maxLength={32}/></label><label>Country code<input name="country" required pattern="[A-Za-z]{2}" maxLength={2} defaultValue="AU" autoComplete="billing country"/></label></div></>}<button className="button primary" disabled={busy}>{busy?'Preparing secure checkout…':(orderId?'Resume this payment':'Continue to payment')}</button></form>:<><p>Order reference: <a href={'/orders/'+payment.orderId}>{payment.orderId}</a></p><p><strong>Amount to pay: {new Intl.NumberFormat('en-AU',{style:'currency',currency:payment.currency}).format(payment.totalMinor/10**(new Intl.NumberFormat('en-AU',{style:'currency',currency:payment.currency}).resolvedOptions().maximumFractionDigits??2))}</strong> <span className="muted">(includes tax of {new Intl.NumberFormat('en-AU',{style:'currency',currency:payment.currency}).format(payment.taxMinor/10**(new Intl.NumberFormat('en-AU',{style:'currency',currency:payment.currency}).resolvedOptions().maximumFractionDigits??2))})</span></p><div ref={target}/><button className="button primary" disabled={busy||!stripeReady||!publishableKey} onClick={pay}>{busy?'Confirming…':'Confirm payment'}</button>{!publishableKey&&<p className="form-error">The payment form’s public key is not configured. Contact support; do not start another order.</p>}</>}{error&&<p className="form-error" role="alert">{error}</p>}<p className="muted">{taxRequired?'Tax is calculated from your billing address.':'Development configuration: tax calculation is disabled.'}</p></section>;
}
