'use client';
import {useState,type FormEvent,type ReactNode} from 'react';import {useRouter} from 'next/navigation';import {api} from '@createcanyon/web/client';
export function MutationForm({path,method='POST',children,submit='Save',transform,redirectTo}:{path:string;method?:string;children:ReactNode;submit?:string;transform?:(data:FormData)=>unknown;redirectTo?:string}){
 const router=useRouter();const [error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setSaved(false);setBusy(true);const form=event.currentTarget;try{const values=new FormData(form);await api(path,{method,body:transform?transform(values):Object.fromEntries(values)});setSaved(true);if(redirectTo)router.push(redirectTo);else router.refresh();}catch(e){setError(e instanceof Error?e.message:'The action failed');}finally{setBusy(false);}}
 return <form className="form-stack" onSubmit={send}>{children}{error&&<p className="form-error" role="alert">{error}</p>}{saved&&<p className="form-status" role="status">Saved successfully.</p>}<button className="button primary" disabled={busy}>{busy?'Saving…':submit}</button></form>;
}
export function ReviewForm({orderLineId}:{orderLineId:string}){return <MutationForm path="reviews" submit="Publish verified review" transform={d=>({orderLineId,rating:Number(d.get('rating')),title:d.get('title'),body:d.get('body')})}><label>Rating<select name="rating" defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label><label>Review title<input name="title" minLength={3} maxLength={120} required/></label><label>Your experience<textarea name="body" minLength={10} maxLength={5000} required/></label></MutationForm>;}
export function SupportForm({orderLineId}:{orderLineId?:string}){return <MutationForm path="support" submit="Open conversation" redirectTo="/support" transform={d=>({subject:d.get('subject'),body:d.get('body'),...(orderLineId?{orderLineId}:{})})}><label>Subject<input name="subject" minLength={5} maxLength={200} required/></label><label>How can we help?<textarea name="body" minLength={10} maxLength={10000} required/></label>{orderLineId&&<p className="muted">This conversation will be linked to your purchase.</p>}</MutationForm>;}
export function ReplyForm({caseId}:{caseId:string}){return <MutationForm path={`support/${caseId}/messages`} submit="Send message"><label>Reply<textarea name="body" minLength={1} maxLength={10000} required/></label></MutationForm>;}
export function SellerCreate(){return <MutationForm path="sellers" submit="Create seller organisation" redirectTo="/seller"><label>Public display name<input name="displayName" minLength={2} maxLength={120} required/></label><label>Legal name<input name="legalName" minLength={2} maxLength={255} required/></label><div className="form-grid"><label>Country code<input name="countryCode" pattern="[A-Z]{2}" defaultValue="AU" maxLength={2} required/></label><label>Business type<select name="businessType"><option value="individual">Individual</option><option value="company">Company</option><option value="non_profit">Non-profit</option></select></label></div><label>Public description<textarea name="description" maxLength={5000}/></label><p className="muted">Your organisation starts pending verification. Payout onboarding and an administrative review are separate from creating this profile.</p></MutationForm>;}
export function TermsAcceptance({sellerId,terms}:{sellerId:string;terms:any}){const [accepted,setAccepted]=useState(false);return <section className="panel"><h2>Seller agreement · {terms.version}</h2><pre className="legal-text">{terms.body_markdown}</pre><label className="check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>I have read and accept this exact version of the seller agreement.</label>{accepted&&<MutationForm path={`sellers/${sellerId}/terms/accept`} submit="Record acceptance" transform={()=>({termsId:terms.id,contentHash:terms.content_hash})}><p className="muted">Acceptance is recorded with the version and content hash.</p></MutationForm>}</section>;}
export function PayoutOnboarding({sellerId}:{sellerId:string}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <><button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const result=await api(`sellers/${sellerId}/payout-onboarding-link`,{method:'POST',body:{returnUrl:window.location.origin+'/seller/'+sellerId}});if(result.url)window.location.assign(result.url);else setError(result.message??'Payout onboarding is unavailable in development stub mode.');}catch(e){setError(e instanceof Error?e.message:'Payout onboarding failed');}finally{setBusy(false);}}}>Set up Stripe payouts</button><p className="muted">Requires recent multi-factor authentication. A new payout account is held for at least 48 hours.</p><a href={'/api/auth/login?stepUp=true&returnTo='+encodeURIComponent('/seller/'+sellerId)}>Reauthenticate with MFA</a>{error&&<p role="alert" className="form-error">{error}</p>}</>;}
export function PriceForm({offer}:{offer:any}){return <MutationForm path={`seller/offers/${offer.id}`} method="PATCH" submit="Update future price" transform={d=>({amountMinor:Number(d.get('amountMinor')),currency:d.get('currency')})}><label>{offer.license_name} price (minor units)<input name="amountMinor" type="number" min="0" max="100000000" step="1" defaultValue={String(offer.amount_minor)} required/></label><label>Currency<input name="currency" pattern="[A-Z]{3}" maxLength={3} defaultValue={offer.currency} required/></label><p className="muted">This changes future purchases only. For USD, 1900 means $19.00. Keep license offers in a consistent currency.</p></MutationForm>;}
export function NewVersion({itemId}:{itemId:string}){return <MutationForm path={`seller/items/${itemId}/versions`} submit="Create immutable release draft"><label>Version label<input name="versionLabel" minLength={1} maxLength={64} required placeholder="2.0.0"/></label><label>Release notes<textarea name="changelog" minLength={5} maxLength={10000} required/></label></MutationForm>;}
export function ListingForm({listing,categories}:{listing:any;categories:any[]}){return <MutationForm path={`seller/listings/${listing.id}`} method="PATCH" submit="Save channel listing" transform={d=>({title:d.get('title'),description:d.get('description'),categoryId:d.get('categoryId')||null,enabled:d.get('enabled')==='on',...(d.get('primary')==='on'?{primary:true}:{})})}><h3>{listing.channel_name}</h3><label>Channel title<input name="title" defaultValue={listing.title} minLength={3} maxLength={180} required/></label><label>Channel description<textarea name="description" defaultValue={listing.description} minLength={20} maxLength={30000} required/></label><label>Category<select name="categoryId" defaultValue={listing.category_id??''}><option value="">Uncategorised</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="check"><input name="enabled" type="checkbox" defaultChecked={listing.enabled}/>Enabled on this channel</label><label className="check"><input name="primary" type="checkbox" defaultChecked={listing.is_primary}/>Make this the primary canonical listing</label></MutationForm>;}
