'use client';import {useState,type FormEvent} from 'react';import {useRouter} from 'next/navigation';import {api} from '@createcanyon/web/client';
interface Channel{id:string;key:string;name:string;eligibleAssetTypes:string[];}
export function ItemCreate({sellerId,channels}:{sellerId:string;channels:Channel[]}){
 const types=[...new Set(channels.flatMap(c=>c.eligibleAssetTypes))].sort();const [type,setType]=useState(types[0]??'PHOTO'),[origin,setOrigin]=useState('createcanyon'),[selected,setSelected]=useState(['createcanyon']),[busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();
 const eligible=channels.filter(c=>c.eligibleAssetTypes.includes(type));
 function chooseType(value:string){setType(value);const allowed=channels.filter(c=>c.eligibleAssetTypes.includes(value)).map(c=>c.key);const newOrigin=allowed.includes(origin)?origin:'createcanyon';setOrigin(newOrigin);setSelected([...new Set([newOrigin,'createcanyon',...allowed.filter(c=>c!=='createcanyon').slice(0,1)])].filter(c=>allowed.includes(c)));}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const d=new FormData(event.currentTarget);const result=await api('seller/items',{method:'POST',body:{sellerOrganisationId:sellerId,assetType:type,originChannelKey:origin,channelKeys:selected,title:d.get('title'),description:d.get('description'),tags:String(d.get('tags')??'').split(',').map(t=>t.trim()).filter(Boolean),metadata:JSON.parse(String(d.get('metadata')||'{}')),aiDisclosure:d.get('aiDisclosure'),basePrice:{amountMinor:Number(d.get('amountMinor')),currency:d.get('currency')},rightsDeclared:d.get('rightsDeclared')==='on'}});router.push('/seller/items/'+result.item.id);}catch(e){setError(e instanceof Error?e.message:'Item creation failed');}finally{setBusy(false);}}
 return <form className="form-stack" onSubmit={submit}><div className="form-grid"><label>Asset type<select value={type} onChange={e=>chooseType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Origin channel<select value={origin} onChange={e=>{setOrigin(e.target.value);setSelected(s=>[...new Set([...s,e.target.value])]);}}>{eligible.map(c=><option value={c.key} key={c.id}>{c.name}</option>)}</select></label></div><fieldset><legend>Publish through these eligible channels</legend>{channels.map(c=><label key={c.id} className="check"><input type="checkbox" disabled={!eligible.some(x=>x.id===c.id)||c.key===origin} checked={selected.includes(c.key)&&eligible.some(x=>x.id===c.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,c.key]:s.filter(k=>k!==c.key))}/>{c.name}{!eligible.some(x=>x.id===c.id)?' — not eligible for this asset type':''}</label>)}</fieldset><label>Canonical title<input name="title" required minLength={3} maxLength={180}/></label><label>Description<textarea name="description" minLength={20} maxLength={30000} required/></label><label>Tags, separated by commas<input name="tags" placeholder="minimal, presentation, annual report"/></label><div className="form-grid"><label>Base price in minor units<input name="amountMinor" type="number" min="0" max="100000000" step="1" required defaultValue="1900"/></label><label>Currency<select name="currency" defaultValue="USD">{['USD','AUD','EUR','GBP','CAD','NZD','JPY'].map(c=><option key={c}>{c}</option>)}</select></label></div><label>AI involvement<select name="aiDisclosure"><option value="NONE">None</option><option value="ASSISTED">AI-assisted</option><option value="GENERATED">AI-generated</option></select></label><details><summary>Technical metadata</summary><label>Metadata object (JSON)<textarea name="metadata" defaultValue="{}" spellCheck={false}/></label><p className="muted">Describe compatibility, included formats, runtime or audio metadata. Values are displayed as text, never executed.</p></details><label className="check"><input type="checkbox" name="rightsDeclared" required/>I own this content or am authorised to sell it, and have redistribution rights for all included components.</label><p className="muted">This creates a draft, not a public listing. Uploads are quarantined and scanned before human moderation.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy||!types.length}>{busy?'Creating draft…':'Create canonical item'}</button></form>;
}
