'use client';
import {useRef,useState} from 'react';import {useRouter} from 'next/navigation';import {api} from '@createcanyon/web/client';import {hashFile} from '@createcanyon/web/sha256';
const MIME:Record<string,string>={zip:'application/zip',tar:'application/x-tar',gz:'application/gzip',tgz:'application/gzip',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',avif:'image/avif',pdf:'application/pdf',mp3:'audio/mpeg',wav:'audio/wav',flac:'audio/flac',ogg:'audio/ogg',m4a:'audio/mp4',ttf:'font/ttf',otf:'font/otf',woff:'font/woff',woff2:'font/woff2',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',txt:'text/plain',md:'text/markdown',csv:'text/csv'};
export function UploadRelease({sellerId,versionId,existingSessionId}:{sellerId:string;versionId:string;existingSessionId?:string}){
 const [files,setFiles]=useState<File[]>([]),[sessionId,setSessionId]=useState(existingSessionId??''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[progress,setProgress]=useState(0);const abort=useRef<AbortController|null>(null);const router=useRouter();
 async function send(){setBusy(true);setError('');setProgress(0);const controller=new AbortController();abort.current=controller;try{
  if(!files.length)throw new Error('Select the original release files. To resume, reselect the same files.');
  const hashes=[];for(const file of files){const ext=file.name.split('.').pop()?.toLowerCase()??'';const contentType=MIME[ext]??file.type;if(!contentType)throw new Error('Unrecognised file extension. Package software as a ZIP archive.');setStatus(`Hashing ${file.name}`);const sha256=await hashFile(file,f=>setProgress(f*100),controller.signal);hashes.push({file,sha256,contentType});}
  let session:any;
  if(sessionId){session=await api('uploads/sessions/'+sessionId);if(session.status!=='UPLOADING')throw new Error('This session is already finalised or cancelled. Reload to see its status.');}
  else {session=await api('uploads/sessions',{method:'POST',body:{sellerOrganisationId:sellerId,itemVersionId:versionId,files:hashes.map(h=>({clientFileId:crypto.randomUUID(),filename:h.file.name,contentType:h.contentType,sha256:h.sha256,byteSize:h.file.size,role:'ORIGINAL'}))}});setSessionId(session.uploadSessionId);}
  const id=session.uploadSessionId;if(session.files.length!==hashes.length)throw new Error('Select the exact set of files from the original upload session.');const used=new Set<number>();let uploaded=0;const total=hashes.reduce((n,h)=>n+h.file.size,0);
  for(const remote of session.files){controller.signal.throwIfAborted();const index=hashes.findIndex((h,i)=>!used.has(i)&&h.sha256===remote.sha256&&h.file.size===remote.byteSize&&h.file.name===remote.filename);if(index<0)throw new Error(`The original file ${remote.filename} was not selected or its content changed.`);used.add(index);const file=hashes[index]!.file;setStatus(`Uploading ${file.name}`);
   if(remote.mode==='single'){const result=await fetch(remote.url,{method:'PUT',headers:remote.headers,body:file,signal:controller.signal,credentials:'omit',redirect:'error'});if(!result.ok)throw new Error(`Object storage rejected ${file.name} (${result.status}). The upload remains resumable.`);uploaded+=file.size;setProgress(100*uploaded/total);}
   else if(remote.mode==='multipart'){
    if(remote.completed){uploaded+=file.size;continue;}
    const present=new Set((remote.parts??[]).map((p:any)=>p.partNumber));
    for(let part=1;part<=remote.partCount;part++){controller.signal.throwIfAborted();const blob=file.slice((part-1)*remote.partSize,Math.min(part*remote.partSize,file.size));if(!present.has(part)){setStatus(`Uploading ${file.name} · part ${part}/${remote.partCount}`);const signed=await api(`uploads/sessions/${id}/files/${remote.id}/parts`,{method:'POST',body:{partNumbers:[part]}});const result=await fetch(signed.parts[0].url,{method:'PUT',body:blob,credentials:'omit',redirect:'error',signal:controller.signal});if(!result.ok)throw new Error(`Part ${part} was rejected by storage (${result.status}). Resume to retry.`);}uploaded+=blob.size;setProgress(100*uploaded/total);}
    await api(`uploads/sessions/${id}/files/${remote.id}/complete`,{method:'POST',body:{}});
   }else throw new Error('This upload session has expired. Cancel it and create a new session.');
  }
  controller.signal.throwIfAborted();setStatus('Finalising the manifest and scheduling security scans…');await api(`uploads/sessions/${id}/finalize`,{method:'POST',body:{files:session.files.map((f:any)=>({clientFileId:f.clientFileId}))}});setProgress(100);setStatus('Submitted. Files remain private while scanning and moderation are in progress.');router.refresh();
 }catch(e){const paused=controller.signal.aborted;setError(paused?'Upload paused. Completed multipart parts are preserved; resume with the same files.':e instanceof Error?e.message:'Upload failed');setStatus(paused?'Paused':'Not submitted');}finally{abort.current=null;setBusy(false);}}
 async function cancel(){if(!sessionId||!window.confirm('Cancel this upload session? Its unfinished file records will be removed.'))return;setBusy(true);try{await api(`uploads/sessions/${sessionId}/cancel`,{method:'POST',body:{}});setSessionId('');setStatus('Upload session cancelled.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'Cancellation failed');}finally{setBusy(false);}}
 return <section className="panel"><h2>{sessionId?'Resume release upload':'Upload original release files'}</h2><p>Files go directly to private quarantine storage. Files larger than 64 MiB use resumable multipart uploads. Archives and uploaded software are never executed.</p><label>Select files<input type="file" multiple disabled={busy} onChange={e=>setFiles([...e.target.files??[]])}/></label><p className="muted">Package code in a ZIP. Supported previews: raster images, audio, PDF and Office documents when their configured processors are available.</p>{files.map((f,i)=><p className="upload-file" key={i}>{f.name} · {(f.size/1024/1024).toFixed(1)} MiB</p>)}<progress className="progress-track" max={100} value={progress} aria-label="Upload progress"/><p role="status">{status}</p>{sessionId&&<p className="muted">Session {sessionId}. This identifier is safe to keep; storage URLs expire independently.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="button-row"><button className="button primary" disabled={busy||!files.length} onClick={send}>{busy?'Processing…':sessionId?'Resume & submit for scanning':'Upload & submit for scanning'}</button>{busy&&<button className="button secondary" onClick={()=>abort.current?.abort()}>Pause upload</button>}{sessionId&&!busy&&<button className="button secondary" onClick={cancel}>Cancel this session</button>}</div></section>;
}
